wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1671861905.859935
    t:
      1:
      - 1
      - 5
      - 9
      - 12
      - 41
      - 45
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 12
      - 41
      - 45
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.15
      5: 0.13.7
      8:
      - 1
      - 5
